start_date: 2022-05-31T18:00:00
end_date: 2023-06-01T12:00:00

checkpoints:
  forecaster:
    checkpoint_path: /leonardo_work/DestE_330_25/anemoi/experiments/ens/checkpoint/315b7030-da27-4665-9517-0b78f9ba199f/inference-last.ckpt
    leadtimes: 120
    static_forcings_dataset: null
    switch_graph: null

dataset: 
  join:
    - dataset: /leonardo_work/DestE_330_25/anemoi/datasets/ERA5/aifs-ea-an-oper-0001-mars-n320-1979-2022-6h-v6.zarr
    - dataset: /leonardo_work/DestE_330_25/anemoi/datasets/ERA5/aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v1-land.zarr
      select: ["lcc", "mcc", "hcc", "tcc", "strd", "ssrd"]
  adjust: ["start", "end"]
frequency: 6h
workdir: .

dataloader:
  datamodule:
    _target_: bris.data.dataset.NativeGridDataset #anemoi.training.data.dataset.ZipDataset
    _convert_: all

#  prefetch_factor: 2
#  num_workers: 1

hardware:
  num_gpus_per_node: ${oc.decode:${oc.env:SLURM_GPUS_PER_NODE}}
  num_nodes: ${oc.decode:${oc.env:SLURM_NNODES}}
  num_gpus_per_model: 1
  num_members: 10

# If the user wants to release GPU cache and memory
# This option releases unused cached/memory used by torch
release_cache: False

model:
  _target_: bris.model.brispredictor.BrisPredictor
  _convert_: all

routing:
  - decoder_index: 0
    domain_index: 0
    outputs:
      #- netcdf:
      #    filename_pattern: /leonardo_work/DestE_330_25/enordhag/bris-inference/netcdf/n320/n320_pred_%Y%m%dT%HZ.nc
      #    variables: [2t, msl, tp]
      #    extra_variables: [ws] #Compute wind speed from 10u and 10v
      - verif:
          filename: /leonardo_work/DestE_330_25/enordhag/bris-inference/verif/2t/n320_at_ref_5d.nc
          variable: 2t
          units: degC
          elev_gradient: -0.0065
          obs_sources:
            - verif:
                filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/t2m/MEPS_2.5km.nc
      - verif:
          filename: /leonardo_work/DestE_330_25/enordhag/bris-inference/verif/ws/n320_at_ref_5d.nc
          variable: ws
          units: m/s
          obs_sources:
            - verif:
                filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/ws10m/MEPS_2.5km.nc
      - verif:
          filename: /leonardo_work/DestE_330_25/enordhag/bris-inference/verif/mslp/n320_at_ref_5d.nc
          variable: msl
          units: hPa
          obs_sources:
            - verif:
                filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/mslp/MEPS_2.5km.nc
      - verif:
          filename: /leonardo_work/DestE_330_25/enordhag/bris-inference/verif/precip6h/n320_at_ref_5d.nc
          variable: tp
          units: mm
          obs_sources:
            - verif:
                filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/precip6h/MEPS_2.5km.nc
