defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_
  
start_date: 2022-05-31T00:00:00
end_date: 2022-07-01T18:00:00
#end_date: 2023-06-01T18:00:00

checkpoints:
  forecaster:
    checkpoint_path: /leonardo_work/DestE_330_25/anemoi/experiments/ens/checkpoint/9fa481ffc3cd457180ee87a2778eb664/inference-last.ckpt
    leadtimes: 40
    static_forcings_dataset: null
    switch_graph: null

timestep: 6h
frequency: 6h
workdir: .

dataset:
  cutout:
    - dataset: ${hardware.paths.data}/MEPS/${hardware.files.dataset_lam}
      reorder: sort
    - dataset:
        join:
          - dataset: ${hardware.paths.data}/IFS/${hardware.files.dataset_atm}
          - dataset: ${hardware.paths.data}/ERA5/${hardware.files.dataset_land}
            select: ["hcc", "mcc", "lcc", "tcc", "strd", "ssrd"]
        adjust: [start, end]
        drop: ["sdor", "slor", "cp", "u_600", "v_600", "z_600", "t_600", "q_600", "w_600"]
      reorder: sort
  adjust: all

dataloader:
  batch_size: 1
  prefetch_factor: 2
  num_workers: 1
  pin_memory: True

  read_group_size: 1 #Do not change this, not implemented properly

  datamodule:
    _target_: bris.data.dataset.NativeGridDataset
    _convert_: all

hardware:
  paths:
    data: /leonardo_work/DestE_330_25/anemoi/datasets
  files:
    dataset_atm: aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
    dataset_land: aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v1-land.zarr
    dataset_lam: aifs-meps-2.5km-2020-2023-6h-v7.zarr
    dataset_obs: name_of_dataset

  num_gpus_per_node: ${oc.decode:${oc.env:SLURM_GPUS_PER_NODE}}
  num_gpus_per_model: 4
  num_members: 10
  num_nodes: ${oc.decode:${oc.env:SLURM_NNODES}}

model:
  _target_: bris.model.brispredictor.BrisPredictor
  _convert_: all

routing:
  - decoder_index: 0
    domain_index: 0
    outputs:
      - netcdf:
          filename_pattern: /leonardo_work/DestE_330_25/enordhag/bris-inference/netcdf/meps/meps_pred_%Y-%m-%dT%HZ.nc
          variables: [2t, msl, tp, lcc, mcc, hcc, tcc] 
          extra_variables: [ws]
      #- verif:
      #    filename: /leonardo_work/EUHPC_R04_079/bris/verification/ens/6h/202206_202305/t2m/meps_at_ref_10d.nc
      #    variable: 2t
      #    units: degC
      #    elev_gradient: -0.0065
      #    obs_sources:
      #      - verif:
      #          filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/t2m/MEPS_2.5km.nc
      #- verif:
      #    filename: /leonardo_work/EUHPC_R04_079/bris/verification/ens/6h/202206_202305/ws10m/meps_at_ref_10d.nc
      #    variable: ws
      #    units: m/s
      #    obs_sources:
      #      - verif:
      #          filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/ws10m/MEPS_2.5km.nc
      #- verif:
      #    filename: /leonardo_work/EUHPC_R04_079/bris/verification/ens/6h/202206_202305/mslp/meps_at_ref_10d.nc
      #    variable: msl
      #    units: hPa
      #    obs_sources:
      #      - verif:
      #          filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/mslp/MEPS_2.5km.nc
      #- verif:
      #    filename: /leonardo_work/EUHPC_R04_079/bris/verification/ens/6h/202206_202305/precip6h/meps_at_ref_10d.nc
      #    variable: tp
      #    units: mm
      #    obs_sources:
      #      - verif:
      #          filename: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/precip6h/MEPS_2.5km.nc
#  - decoder_index: 0
#    domain_index: 1
#    outputs:
#      - netcdf:
#          filename_pattern: /leonardo_work/DestE_330_25/enordhag/bris-inference/netcdf/era_pred_%Y-%m-%dT%H.nc
#          variables: [2t, msl, tp, lcc, mcc, hcc, tcc] #, 10u, 10v]
#          extra_variables: [ws]
#          # interp_res: 0.25
